Repository MisterPeModder/JobBoard, pull requests merged in 2022-10, with the labels that each got.

#21 Add Base Job Listings Front Page
  app/Providers/AppServiceProvider.php
  app/View/Components/JobAdvert.php
  app/View/Components/Layout.php
  app/View/Components/PageNavigation.php
  package-lock.json
  package.json
  postcss.config.js
  public/hamburger.png
  public/star.svg
  resources/css/app.css
  resources/images/delete-src.svg
  resources/images/delete.svg
  resources/images/flag-src.svg
  resources/images/flag.svg
  resources/images/hamburger-src.svg
  resources/images/hamburger.svg
  resources/images/location-src.svg
  resources/images/location.svg
  resources/images/profiles/acme.svg
  resources/images/profiles/web-sys.svg
  resources/images/search-src.svg
  resources/images/search.svg
  resources/images/star-outline-src.svg
  resources/images/star-outline.svg
  resources/images/star-src.svg
  resources/images/star.svg
  resources/images/three-dots-src.svg
  resources/images/three-dots.svg
  resources/js/app.js
  resources/js/app.ts
  resources/js/functional.ts
  resources/js/jobAdverts.ts
  resources/views/components/job-advert.blade.php
  resources/views/components/layout.blade.php
  resources/views/components/page-navigation.blade.php
  resources/views/job-list.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tailwind.config.js
  tsconfig.json
  vite.config.js
Labels: ui/ux

#23 Implement the Blob and Asset system
  app/Http/Controllers/AssetController.php
  app/Models/ApplicationAttachment.php
  app/Models/Asset.php
  app/Models/Blob.php
  app/Models/Company.php
  app/Models/User.php
  composer.json
  composer.lock
  config/filesystems.php
  database/factories/AdvertFactory.php
  database/factories/ApplicationAttachmentFactory.php
  database/factories/AssetFactory.php
  database/factories/BlobFactory.php
  database/factories/CompanyFactory.php
  database/migrations/2022_09_28_124725_create_users_table.php
  database/migrations/2022_09_28_135435_create_adverts_table.php
  database/migrations/2022_09_28_135457_create_blobs_table.php
  database/migrations/2022_09_28_135515_create_companies_table.php
  database/migrations/2022_09_28_135547_create_applications_table.php
  database/migrations/2022_09_28_135627_create_applicationattachments_table.php
  database/migrations/2022_10_04_215510_create_assets_table.php
  database/schema/mysql-schema.dump
  database/seeders/DatabaseSeeder.php
  routes/console.php
  routes/web.php
  storage/app/.gitignore
  storage/app/blobs/.gitignore
  storage/app/examples/1.jpg
  storage/app/examples/10.webp
  storage/app/examples/11.webp
  storage/app/examples/12.webp
  storage/app/examples/13.webp
  storage/app/examples/14.webp
  storage/app/examples/15.webp
  storage/app/examples/16.webp
  storage/app/examples/3.jpg
  storage/app/examples/4.jpg
  storage/app/examples/5.jpg
  storage/app/examples/6.jpg
  storage/app/examples/7.jpg
  storage/app/examples/8.jpg
  storage/app/examples/9.webp
Labels: database

#29 Display Job Adverts From the Database into the Main Page
  app/Enums/Currency.php
  app/Enums/JobType.php
  app/Enums/SalaryType.php
  app/Enums/StringEnum.php
  app/Http/Controllers/AssetController.php
  app/Http/Controllers/JobListController.php
  app/Models/Advert.php
  app/Models/Asset.php
  app/Models/Company.php
  app/Providers/AppServiceProvider.php
  app/View/Components/JobAdvert.php
  database/factories/AdvertFactory.php
  database/migrations/2022_10_05_084631_add_advert_fields.php
  database/seeders/DatabaseSeeder.php
  lang/en.json
  resources/views/components/job-advert.blade.php
  resources/views/job-list.blade.php
  routes/web.php
Labels: REST API

#32 Add Job Application Form
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/JobApplicationController.php
  app/Http/Requests/StoreJobApplicationRequest.php
  app/Http/Requests/UpdateJobApplicationRequest.php
  app/Models/Advert.php
  app/Models/Application.php
  app/Models/ApplicationAttachment.php
  app/Models/Asset.php
  app/Models/User.php
  app/View/Components/AppLayout.php
  app/View/Components/GuestLayout.php
  app/View/Components/Layout.php
  database/factories/AssetFactory.php
  database/factories/BlobFactory.php
  database/migrations/2022_10_07_075551_add_users_phone_number_column.php
  database/migrations/2022_10_07_102351_make_user_password_nullable.php
  database/seeders/DatabaseSeeder.php
  lang/en.json
  lang/en/validation.php
  resources/css/common.css
  resources/js/app.ts
  resources/js/common.ts
  resources/js/jobAdverts.ts
  resources/js/jobApplication.ts
  resources/views/auth/confirm-password.blade.php
  resources/views/auth/forgot-password.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/reset-password.blade.php
  resources/views/auth/verify-email.blade.php
  resources/views/components/auth-card.blade.php
  resources/views/components/blank-layout.blade.php
  resources/views/components/input-error.blade.php
  resources/views/components/job-advert.blade.php
  resources/views/components/main-layout.blade.php
  resources/views/components/primary-button.blade.php
  resources/views/components/text-area.blade.php
  resources/views/components/text-input.blade.php
  resources/views/dashboard.blade.php
  resources/views/job-application.blade.php
  resources/views/job-list.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/navigation.blade.php
  routes/web.php
  vite.config.js
Labels: ui/ux, REST API

#35 Add CRUD operations for companies
  .env.example
  app/Http/Controllers/CompanyController.php
  app/Http/Controllers/JobApplicationController.php
  app/Http/Controllers/JobListController.php
  app/Http/Requests/StoreCompanyRequest.php
  app/Http/Requests/UpdateCompanyRequest.php
  app/Models/Company.php
  app/Models/User.php
  app/Policies/CompanyPolicy.php
  app/Providers/AuthServiceProvider.php
  app/View/Components/CompanyEntry.php
  app/View/Components/JobAdvert.php
  database/migrations/2022_10_04_215510_create_assets_table.php
  database/migrations/2022_10_07_141741_convert_descriptions_to_text.php
  database/migrations/2022_10_08_165556_relax_fk_constraints.php
  lang/en.json
  resources/images/gear-src.svg
  resources/images/gear.svg
  resources/images/left-angle-src.svg
  resources/images/left-angle.svg
  resources/js/components/advertOptions.ts
  resources/js/components/exclusiveDetails.ts
  resources/js/components/imageInput.ts
  resources/js/functional.ts
  resources/js/jobApplication.ts
  resources/views/companies/create.blade.php
  resources/views/companies/edit.blade.php
  resources/views/companies/list.blade.php
  resources/views/companies/show.blade.php
  resources/views/components/advert-options.blade.php
  resources/views/components/company-entry.blade.php
  resources/views/components/company-member.blade.php
  resources/views/components/exclusive-details.blade.php
  resources/views/components/image-input.blade.php
  resources/views/components/input-label.blade.php
  resources/views/components/job-advert.blade.php
  resources/views/components/main-layout.blade.php
  resources/views/components/page-navigation.blade.php
  resources/views/components/primary-button.blade.php
  resources/views/components/primary-link.blade.php
  resources/views/components/secondary-link.blade.php
  resources/views/job-application.blade.php
  resources/views/job-list.blade.php
  routes/web.php
  tsconfig.json
  vite.config.js
Labels: enhancement, ui/ux, REST API

#40 Add main page
  resources/css/common.css
  resources/views/main-page.blade.php
  routes/web.php
Labels: ui/ux

#42 Add 404 page
  lang/en.json
  resources/views/errors/404.blade.php
Labels: ui/ux

#43 Check user permissions when accessing assets
  app/Http/Controllers/AdvertApplicationController.php
  app/Http/Controllers/AssetController.php
  app/Http/Controllers/CompanyController.php
  app/Http/Requests/StoreAdvertApplicationRequest.php
  app/Policies/AssetPolicy.php
  database/factories/AssetFactory.php
  database/seeders/DatabaseSeeder.php
Labels: database

#44 Implement searching & filtering for the adverts list
  app/Http/Controllers/AdvertController.php
  app/Http/Controllers/CompanyController.php
  app/Models/Advert.php
  composer.json
  composer.lock
  config/scout.php
  lang/en.json
  resources/views/jobs/list.blade.php
  resources/views/main-page.blade.php
Labels: ui/ux

#46 Implement Functionality of the "Hamburger" Menu
  lang/en.json
  resources/js/components/hamburgerMenu.ts
  resources/views/components/advert-options.blade.php
  resources/views/components/blank-layout.blade.php
  resources/views/components/exclusive-details.blade.php
  resources/views/components/hamburger-menu.blade.php
  resources/views/components/hamburger-toggle-button.blade.php
  resources/views/components/image-input.blade.php
  resources/views/components/main-layout.blade.php
  routes/web.php
  vite.config.js
Labels: ui/ux

#55 Create admin-only menus for editing companies
  app/Http/Controllers/CompanyController.php
  app/Http/Requests/StoreCompanyRequest.php
  app/Http/Requests/UpdateCompanyRequest.php
  app/Providers/AuthServiceProvider.php
  app/View/Components/CompanyEntry.php
  lang/en.json
  resources/views/admin.blade.php
  resources/views/companies/create.blade.php
  resources/views/companies/edit.blade.php
  resources/views/companies/list.blade.php
  resources/views/companies/show.blade.php
  resources/views/components/blank-layout.blade.php
  resources/views/components/company-entry.blade.php
  resources/views/components/company-member.blade.php
  resources/views/components/main-layout.blade.php
  resources/views/components/primary-button.blade.php
  resources/views/components/primary-link.blade.php
  resources/views/components/secondary-link.blade.php
  resources/views/main-page.blade.php
  routes/web.php
  tailwind.config.js
Labels: ui/ux, admin

#57 Feature/13 french localization
  app/Http/Kernel.php
  app/Http/Middleware/LanguageManager.php
  lang/en.json
  lang/fr.json
  lang/fr/auth.php
  lang/fr/pagination.php
  lang/fr/passwords.php
  lang/fr/validation.php
  resources/views/auth/register.blade.php
  resources/views/components/blank-layout.blade.php
  resources/views/components/main-layout.blade.php
  resources/views/main-page.blade.php
  resources/views/pagination.blade.php
  routes/web.php
Labels: ui/ux

#58 Remove unused buttons (favorite, report, not interested)
  resources/js/components/advertOptions.ts
  resources/views/components/advert-options.blade.php
  resources/views/components/job-advert.blade.php
Labels: ui/ux

#59 Create admin-only menus for editing assets
  app/Http/Controllers/AssetController.php
  app/Http/Requests/UpdateAssetRequest.php
  lang/en.json
  lang/fr.json
  resources/views/admin.blade.php
  resources/views/assets/edit.blade.php
  resources/views/assets/list.blade.php
  resources/views/companies/create.blade.php
  resources/views/components/asset-entry.blade.php
  resources/views/pagination.blade.php
Labels: ui/ux, admin

#61 Rename site to "OnlyBoard" and add logo
  .env.example
  README.md
  config/app.php
  resources/images/logo-src.svg
  resources/images/logo.svg
  resources/views/components/blank-layout.blade.php
  resources/views/components/main-layout.blade.php
  resources/views/main-page.blade.php
Labels: ui/ux
